### ISSUE TITLE
Ordering breaking with pytest-xdist + pytest-dependency

### ISSUE THREAD

**Issue by hnandiwada** [pytest-dev/pytest-order#71] opened 2023-05-23 23:22 UTC
Hi,
I have the following test code:
```
class BaseTest:
   ...

    @pytest.mark.dependency(name="one", depends=["zero"])
    def test_one(self, fixtures...):
        ...

    @pytest.mark.dependency(name="two", depends=["one"])
    def test_two(self, fixtures...):
        ...

    @pytest.mark.dependency(name="three", depends=["two"])
    def test_three(self, fixtures...):
        ...

    @pytest.mark.dependency(name="zero")
    def test_zero(self, fixtures...):
        ...
```

Other tests inherit from the BaseTest. Every class has its own file.
```
class TestSomething(BaseTest):
    @pytest.fixture(scope="module")
    def something(self):
        return "something"
```
I've been running `python3 -m pytest -s --order-dependencies -ra -v --dist=loadfile -n auto`.

The first ordering works well - zero runs before one for every class that inherits the test. But, for some reason, pytest-order is consistently putting test_three before test_two (except for one class in particular - not sure if this is a red herring or not). I'm not sure if this is a bug or some behavior that I don't understand. I can confirm the order that the tests are being run in in the verbose output. Everything runs correctly when running without xdist: `python3 -m pytest -s --order-dependencies -ra -v -k something`.
Happy to share more details privately if they would help.
Thanks for maintaining such a useful plugin!

**Comment by mrbean-bremen** [comment] 2023-05-24 17:11
Thanks for the report! 
At first glance, I see nothing that would cause this - you use `--dist=loadfile`, and there are no dependencies between your modules. The setup with the base class is a bit unusual though, and certainly nothing I had tested so far - I suspect that the problem is somehow related to that, but that is only a guess.
I will try to reproduce the problem, and in case I can't, ask for more information.

**Comment by mrbean-bremen** [comment] 2023-05-24 18:19
A couple of questions:
- Do you also use the option `--order-scope=module`? You probably should, otherwise the ordering will be done globally (though actually this is something that could be done automatically if `xdist` is detected - haven't thought about this before)
- Do you get any warnings from `pytest-order`, e.g. `WARNING: cannot execute test relative to others: ...`? Maybe you can show the relevant part of the output.

**Comment by mrbean-bremen** [comment] 2023-06-01 18:31
Thank you - I will see if I can find out anything, though that will take some time (won't have access to a computer for at least a week, and there are other issues to handle first afterwards). Anyway, if you don't use it anymore, you will be in no rush to have this fixed...

**Comment by mrbean-bremen** [comment] 2024-02-16 19:18
I had forgotten about this one... I just had another look and found that the problem may appear even without `xdist`. 

The root cause is that `pytest-order` does not correctly handle several markers with the same dependency name (in this case "zero", "one" etc, which are used in each derived class). I made the assumption that the test name would always be unique, but this is obviously not the case here.

**Closed** 2024-02-17 08:37 UTC
Labels: bug
